services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=App!ication123
      - MYSQL_DATABASE=ecommerce
    volumes:
      - ./data/mysql/:/var/lib/mysql

networks:
  default:
    driver: bridge